import './test/2d/shader.spec.ts';
import './test/2d/sprite.spec.ts';
import './test/2d/transform.spec.ts';
import './test/core/drawable.spec.ts';
import './test/core/framebuffer.spec.ts';
import './test/core/renderer.spec.ts';
import './test/core/shader.spec.ts';
import './test/core/texture.spec.ts';
import './test/core/vertex-buffer.spec.ts';
import './test/gltf/loader.spec.ts';
import { getTests } from 'test';
import Reporter from './src/reporter';
new Reporter(getTests()).run();