export enum GlFramebufferParam {
    FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0, 
    FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1, 
    FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2, 
    FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3, 
}