export enum GlRenderbufferParam {
    RENDERBUFFER_WIDTH = 0x8D42, 
    RENDERBUFFER_HEIGHT = 0x8D43, 
    RENDERBUFFER_INTERNAL_FORMAT = 0x8D44, 
    RENDERBUFFER_RED_SIZE = 0x8D50, 
    RENDERBUFFER_GREEN_SIZE = 0x8D51, 
    RENDERBUFFER_BLUE_SIZE = 0x8D52, 
    RENDERBUFFER_ALPHA_SIZE = 0x8D53, 
    RENDERBUFFER_DEPTH_SIZE = 0x8D54, 
    RENDERBUFFER_STENCIL_SIZE = 0x8D55, 
}